apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: frinx
    jsonData:
      defaultBucket: frinx
      httpMode: POST
      organization: frinx-machine
      version: Flux
      timeout: 600
    secureJsonData:
      basicAuthPassword: frinx123!
      token: eyJrIjoiN09MSVpVZjlVRG1xNHlLNXpVbmZJOXFLWU1GOXFxNEIiLCJuIjoic3Nzc3MiLCJpZCI6MX0
