{
 "title": "Conductor workflows monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workflow",
    "label": "Select workflow",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"workflowName\",\n)"
   }
  ]
 },
 "panels": [
  { "title": "Global metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "by_status = from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> last()\n  |> drop(columns: [\"workflowName\", \"_field\"])\n  |> sum()\n\ntogether = by_status\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"SUM\"})\n\nunion(tables: [by_status,together])\n\n"
    }
   ]
  },
  {
   "title": "Running workflows",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_running\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n"
    }
   ]
  },
  {
   "title": "All running workflows",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_running\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield(name: \"running\")\n"
    }
   ]
  },
  { "title": "${workflow}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Per ${workflow} executions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "diff_time = from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"workflowName\"] == \"${workflow}\")\n  |> difference()\n\nby_status = diff_time\n  |> keep(columns: [\"table\", \"_value\", \"status\"])\n  |> sum()\n  \ntogether = diff_time\n  |> group()\n  |> sum(column: \"_value\")\n  |> set(key: \"status\", value: \"SUM\")\n\nunion(tables: [by_status,together])\n"
    }
   ]
  },
  {
   "title": "Max ${workflow} execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_completed_seconds_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> filter(fn: (r) => r[\"workflowName\"] == \"${workflow}\")\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Mean ${workflow} execution time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"0.99\")\n  |> filter(fn: (r) => r[\"workflowName\"] == \"${workflow}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Running ${workflow}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Polling frequency" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"workflow_running\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> filter(fn: (r) => r[\"workflowName\"] == \"${workflow}\")\n"
    }
   ]
  }
 ]
}