{
 "title": "Conductor tasks monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "task",
    "label": "Select tasks",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"taskType\",\n)"
   }
  ]
 },
 "panels": [
  { "title": "Global metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "by_status = from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"task_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> last()\n  |> drop(columns: [\"taskType\", \"_field\"])\n  |> sum()\n\ntogether = by_status\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"SUM\"})\n\nunion(tables: [by_status,together])\n\n"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"task_in_progress\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")"
    }
   ]
  },
  { "title": "${task}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Per ${task} executions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "a = from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"task_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"taskType\"] == \"${task}\")\n  |> aggregateWindow(every: 10s, fn: distinct, createEmpty: true)\n\nb = a\n  |> first()\n\nc = a\n  |> last()\n\ndiff_tab = union(tables: [b,c])\n |> spread()\n\nby_status = diff_tab\n  |> keep(columns: [\"table\", \"_value\", \"status\"])\n  |> sum()\n  \ntogether = diff_tab\n  |> group()\n  |> sum(column: \"_value\")\n  |> set(key: \"status\", value: \"SUM\")\n\nunion(tables: [by_status,together])\n"
    }
   ]
  },
  {
   "title": "Mean ${task} execution time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"task_completed_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] != \"sum\" and r[\"_field\"] != \"count\")\n  |> filter(fn: (r) => r[\"taskType\"] == \"${task}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Max ${task} execution time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"task_completed_seconds_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> filter(fn: (r) => r[\"taskType\"] == \"${task}\")\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Mean ${task} execution time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"update_task_dao_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] != \"sum\" and r[\"_field\"] != \"count\")\n  |> filter(fn: (r) => r[\"taskType\"] == \"${task}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Update ${task} DAO Max",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"update_task_dao_seconds_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> filter(fn: (r) => r[\"taskType\"] == \"${task}\")\n  |> max()\n\n"
    }
   ]
  }
 ]
}