{
 "title": "PostgresQL monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Select database",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"db\",\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Num Backends",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"numbackends\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Max Written Clean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"maxwritten_clean\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deadlocks\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"com.docker.stack.namespace\"] == \"fm\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"com.docker.swarm.service.name\"] == \"fm_postgresql\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Datname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"datname\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Datid",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"datid\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"conflicts\" )\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> filter(fn: (r) => r[\"com.docker.swarm.service.name\"] == \"fm_postgresql\")\n  |> filter(fn: (r) => r[\"com.docker.stack.namespace\"] == \"fm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Commit and Rollback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "XACT Commit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"xact_commit\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "XACT Commit derivative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"xact_commit\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> increase()\n  |> derivative()"
    }
   ]
  },
  {
   "title": "XACT Rollback",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"xact_rollback\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "XACT Rollback derivative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"xact_rollback\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> increase()\n  |> derivative()"
    }
   ]
  },
  { "title": "BLK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Blk read time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blk_read_time\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Blk write time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blk_write_time\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Blks hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_hit\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n"
    }
   ]
  },
  {
   "title": "Blks read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_read\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n\n"
    }
   ]
  },
  {
   "title": "Blks hits derivative",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_hit\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> increase()\n  |> derivative()"
    }
   ]
  },
  {
   "title": "Blks read derivative",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_read\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> increase()\n  |> derivative()\n"
    }
   ]
  },
  {
   "title": "Blks hits last",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_hit\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Blks read last",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_read\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> last()"
    }
   ]
  },
  { "title": "TUP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tup_deleted\" or r[\"_field\"] == \"tup_fetched\" or r[\"_field\"] == \"tup_inserted\" or r[\"_field\"] == \"tup_returned\" or r[\"_field\"] == \"tup_updated\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Buffers mean",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"buffers_alloc\" or r[\"_field\"] == \"buffers_backend\" or r[\"_field\"] == \"buffers_backend_fsync\" or r[\"_field\"] == \"buffers_clean\" or r[\"_field\"] == \"buffers_checkpoint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"checkpoint_sync_time\" or r[\"_field\"] == \"checkpoint_write_time\" or r[\"_field\"] == \"checkpoints_timed\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"frinx\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"checkpoints_req\")\n  |> filter(fn: (r) => r[\"db\"] == \"${database}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}