version: "3.7"

x-logging: &logging_loki
    driver: loki
    options:
      loki-url: "http://${MANAGER_IP_ADDR}:3100/loki/api/v1/push"
      max-file: "3"
      max-size: "10m"
      mode: non-blocking
      loki-retries: "1"
      loki-batch-size: "1500"
      loki-relabel-config: |
        - action: labelmap
          regex: swarm_(service)

x-logging: &logging_json
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"

services:
  krakend:
    image: frinx/krakend:${LOCAL_KRAKEND_IMAGE_TAG}
    # user: root
    logging: *logging_loki
    labels:
      - traefik.enable=false  
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/settings
      - FC_PARTIALS=/etc/krakend/partials
      - FC_TEMPLATES=/etc/krakend/templates
      # - FC_OUT=/etc/krakend/output.json
    # TODO fix x509 certificate errors
      - GODEBUG="x509ignoreCN=0"
    volumes:
      - ${UF_CONFIG_PATH}/krakend:/etc/krakend:ro
      - ${UF_CONFIG_PATH}/krakend/tls/${KRAKEND_TLS_PROTOCOL}:/etc/krakend/partials/tls:ro
    secrets:
      - frinx_krakend_tls_cert.pem
      - frinx_krakend_tls_key.pem
    healthcheck:
      test: curl --silent --write-out 'HTTPSTATUS:%{http_code}' -X GET 'http://127.0.0.1:8080/__health' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - target: 8080
        published: ${KRAKEND_PORT}
        mode: host # This makes host to listen on 0.0.0.0:${KRAKEND_PORT} 
                   # It is the same as you would expect when publishing a port when not running in swarm mode. 
                   # It is NOT host networking in plain docker.
    ulimits:
      nofile:
        soft: ${KD_ULIMIT_NOFILE_SOFT}
        hard: ${KD_ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${KD_ULIMIT_NPROC_SOFT}
        hard: ${KD_ULIMIT_NPROC_HARD}
    cap_drop:
      - all
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${KD_RES_LIMIT_CPUS}
          memory: ${KD_RES_LIMIT_MEM}
secrets:
  frinx_krakend_tls_cert.pem:
    external: true
  frinx_krakend_tls_key.pem:
    external: true

networks:
    default:
      name: frinx-machine