# THIS FILE IS USED AS A TEMPLATE FOR UNICONFIG SERVICES
# DO NOT DEPLOY SERVICES USING THIS FILE
# USE ./startup.sh SCRIPT TO DO IT FOR YOU
# ${UC_CONFIG_PATH} and ${LICENSE} ARE SET BY THE ./startup.sh SCRIPT

version: "3.7"

x-logging: &logging_loki
    driver: loki
    options:
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
      max-file: "3"
      max-size: "10m"
      mode: non-blocking
      keep-file: "false"
      loki-retries: "1"
      loki-batch-size: "1500"
      loki-relabel-config: |
        - action: labelmap
          regex: swarm_(service)

x-placement: &placement
      placement:
        constraints:
          - node.role == manager

x-tcp_keepalive: &tcp_keepalive
      net.ipv4.tcp_keepalive_time: 300

x-traefik-label: &traefik_labels
      - traefik.enable=false

services:
  unistore:
    image: frinx/uniconfig:latest
    logging: *logging_loki
    labels:
      - traefik.enable=false  
    environment:
      - CONTAINER_ID={{.Task.Slot}}
      - SERVICE_NAME={{.Service.Name}}
      - JAVA_MAX_MEM=${US_XMX_LIMIT_MEM}
      # Enable G1GC and GC logging 
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
      - _JAVA_OPTIONS=-Xmx${US_XMX_LIMIT_MEM} -XX:+AlwaysPreTouch -Djna.nosys=true -XX:+CrashOnOutOfMemoryError -XX:MaxGCPauseMillis=200 -Xlog:gc:/opt/uniconfig-frinx/log/gc.log:tags,time,uptime,level:filecount=10,filesize=5M -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1
      # DBPERSISTANCE CONNECTION PARAMETERS, CREDENTIALS STORED IN SECRETS
      - DBPERSISTENCE_EMBEDDEDDATABASE_ENABLED=false
      - DBPERSISTENCE_CONNECTION_DATABASELOCATIONS_0_HOST=unistore-postgres
      - DBPERSISTENCE_CONNECTION_DATABASELOCATIONS_0_PORT=5432
      - DBPERSISTENCE_CONNECTION_MAXDBPOOLSIZE=300
      # UNISTORE TRANSACTIONS CONFIGURATION
      - TRANSACTIONS_TRANSACTIONIDLETIMEOUT=3600
      - TRANSACTIONS_MAXTRANSACTIONAGE=7200
    volumes:
      - frinx_unistore-controller_logs:/opt/uniconfig-frinx/log
      - ${UF_CONFIG_PATH}/unistore/cache:/opt/uniconfig-frinx/cache:rw
    secrets:
      - frinx_unistore_db
    configs:
      - source: unistore_startup
        target: /opt/uniconfig-frinx/run_uniconfig.sh
        mode: 0555
      - source: set_env_secrets
        target: /set_env_secrets.sh
        mode: 0555
      - source: unistore_logback
        target: /opt/uniconfig-frinx/config/logback.xml
        mode: 0555
    healthcheck:
      test: | 
        curl --insecure -o /dev/null --silent --write-out "%{http_code}" \
        -X POST 'http://127.0.0.1:8181/rests/operations/uniconfig-manager:health' \
        -H "Content-Type:application/json" | grep 200 || exit 1
      interval: 10s
      timeout: 35s
      retries: 5
      start_period: ${US_HEALTH_START_TIME}
    entrypoint: ['/opt/uniconfig-frinx/run_uniconfig.sh']
    ulimits:
      nofile:
        soft: ${US_ULIMIT_NOFILE_SOFT}
        hard: ${US_ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${US_ULIMIT_NPROC_SOFT}
        hard: ${US_ULIMIT_NPROC_HARD}
    cap_drop:
      - all
    cap_add:
      - CAP_NET_BIND_SERVICE
      - NET_ADMIN
    sysctls:
      <<: *tcp_keepalive
    deploy: 
      labels: *traefik_labels
      <<: *placement
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${US_RES_LIMIT_CPUS}
          memory: ${US_RES_LIMIT_MEM}

  unistore-postgres:
    image: postgres:12.10
    user: postgres
    logging: *logging_loki
    labels:
      - traefik.enable=false  
    volumes:
      - frinx_unistore-postgresql_data:/var/lib/postgresql/data
    secrets:
      - frinx_unistore_db
    entrypoint: ["/set_env_secrets.sh","docker-entrypoint.sh"]
    command: 
      - postgres
      - -c max_connections=300 
    configs:
      - source: set_env_secrets
        target: /set_env_secrets.sh
        mode: 0555
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ulimits:
      nofile:
        soft: ${SP_ULIMIT_NOFILE_SOFT}
        hard: ${SP_ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${SP_ULIMIT_NPROC_SOFT}
        hard: ${SP_ULIMIT_NPROC_HARD}
    cap_drop:
      - all
    cap_add:
      - CAP_NET_BIND_SERVICE
      - NET_ADMIN
    sysctls:
      <<: *tcp_keepalive
    deploy: 
      <<: *placement
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${SP_RES_LIMIT_CPUS}
          memory: ${SP_RES_LIMIT_MEM}

volumes:
  frinx_unistore-controller_logs:
    name: frinx_unistore_logs
  frinx_unistore-postgresql_data:
    name: frinx_unistore-postgresql_data

configs:
  unistore_startup:
    name: unistore_startup-${DEPLOY_SETTINGS_TIMESTAMP}.yml
    file: ${UF_CONFIG_PATH}/uniconfig/run_uniconfig.sh
  unistore_logback:
    name: unistore_logback-${DEPLOY_SETTINGS_TIMESTAMP}.yml
    file: ${UF_CONFIG_PATH}/unistore/logback.xml
  set_env_secrets:
    file: ${UF_CONFIG_PATH}/set_env_secrets.sh

secrets:
  frinx_unistore_db:
    external: true

networks:
    default:
      name: frinx-machine
      driver: overlay
