version: "3.7"

services:
  micros:
    image: frinx/uniflow-micros:latest
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      - UNICONFIG_URL_BASE=https://${UNICONFIG_SERVICENAME}:8181/rests
    healthcheck:
      test: cat /home/app/healthcheck && curl --insecure --write-out 'HTTPSTATUS:%{http_code}' --silent --fail -X GET http://conductor-server:8080/api/health && curl --silent --fail --write-out 'HTTPSTATUS:%{http_code}' -X GET 'http://workflow-proxy:8088/probe/readiness'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ulimits:
      nofile:
        soft: ${MC_ULIMIT_NOFILE_SOFT}
        hard: ${MC_ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${MC_ULIMIT_NPROC_SOFT}
        hard: ${MC_ULIMIT_NPROC_HARD}
    cap_drop:
      - all
    deploy:
      placement:
        constraints:
          - node.id == ${CONSTRAINT_ID}
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 10s
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${MC_RES_LIMIT_CPUS}
          memory: ${MC_RES_LIMIT_MEM}
