version: "3.7"

services:
  uniconfig:
    image: traefik:v2.4
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    volumes:
      - ${UF_CONFIG_PATH}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${UF_CONFIG_PATH}/traefik/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - frinx_uniconfig_tls_cert.pem
      - frinx_uniconfig_tls_key.pem
      - frinx_uniconfig_X509.crt
    healthcheck:
      test: traefik healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ulimits:
      nofile:
        soft: ${TF_ULIMIT_NOFILE_SOFT}
        hard: ${TF_ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${TF_ULIMIT_NPROC_SOFT}
        hard: ${TF_ULIMIT_NPROC_HARD}
    # cap_drop:
    #   - all
    deploy:
      placement:
        constraints:
          - node.id == ${UF_SWARM_NODE_ID}
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${TF_RES_LIMIT_CPUS}
          memory: ${TF_RES_LIMIT_MEM}

networks:
  default:
    name: frinx-machine

secrets:
  frinx_uniconfig_tls_cert.pem:
    external: true
  frinx_uniconfig_tls_key.pem:
    external: true
  frinx_uniconfig_X509.crt:
    external: true