version: "3.7"

services:
  uniconfig:
    image: traefik:v2.4
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    volumes:
      - ${UF_CONFIG_PATH}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    # healthcheck:
    #   test: traefik healthcheck
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
    # ulimits:
    #   nofile:
    #     soft: ${KD_ULIMIT_NOFILE_SOFT}
    #     hard: ${KD_ULIMIT_NOFILE_HARD}
    #   nproc:
    #     soft: ${KD_ULIMIT_NPROC_SOFT}
    #     hard: ${KD_ULIMIT_NPROC_HARD}
    # cap_drop:
    #   - all
    deploy:
      placement:
        constraints:
          - node.id == ${UF_SWARM_NODE_ID}
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: ${KD_RES_LIMIT_CPUS}
      #     memory: ${KD_RES_LIMIT_MEM}

networks:
  default:
    name: frinx-machine
