# UniFlow containers
version: "3.7"

services:
  api-gateway:
    image: frinx/api-gateway:2.0.0
    environment:
      - API_GATEWAY_HOST=api-gateway:5000
      - DASHBOARD_HOST=dashboard:8888
      - UNIFLOW_UI_HOST=uniflow-ui:3000
      - UNIFLOW_API_HOST=uniflow-api:3001
      - UNICONFIG_UI_HOST=uniconfig-ui:4000
      - UNICONFIG_API_HOST=${CONSTRAINT_HOSTNAME}_uniconfig:8181
      # TODO: Make uniconfig-ui able to route to multiple UNICONFIG_API_HOSTs, see uniconfig-ui service
      # Currently working on local deployment only
      - API_GATEWAY_HTTPS=${API_GATEWAY_HTTPS}
      - UNICONFIG_UI_PROTOCOL=https
      - UNICONFIG_API_PROTOCOL=https
    volumes:
      - ${UF_CONFIG_PATH}/api-gateway:/api-gateway/certificates
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    ports:
      - target: 5000
        published: ${API_GATEWAY_PORT}
        mode: host # This makes host to listen on 0.0.0.0:${API_GATEWAY_PORT} 
                   # It is the same as you would expect when publishing a port when not running in swarm mode. 
                   # It is NOT host networking in plain docker.
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1
    healthcheck:
      test: curl --insecure --silent --write-out 'HTTPSTATUS:%{http_code}' -X GET '${API_GATEWAY_HEALTHCHECK_PROTOCOL}://127.0.0.1:5000/uniflow/ui'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: frinx/uniflow-conductor-server:1.0.0
    volumes:
      -  ${UF_CONFIG_PATH}/conductor/config.properties:/app/config/config.properties
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1
    healthcheck:
      test: wget -O- localhost:8080/api/health
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      - uniflow_elastic_data:/usr/share/elasticsearch/data
      -  ${UF_CONFIG_PATH}/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      -  ${UF_CONFIG_PATH}/elasticsearch/backup.sh:/usr/share/elasticsearch/backup.sh
    healthcheck:
      test: curl -X GET 'localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1

  dashboard:
    # TODO: make stable release and change 'latest' version to a stable one
    image: frinx/frinx-frontend:latest
    ports:
      - 8888:8888
    volumes:
      - ${UF_CONFIG_PATH}/frinx-frontend/config.json:/usr/share/nginx/html/config.json
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    healthcheck:
      test: curl --silent -o /dev/null  --write-out 'HTTPSTATUS:%{http_code}\n' -X GET 'http://127.0.0.1:8888' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgresql:
    image: postgres:12.2
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=conductor,frinx,schellar
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - uniflow_postgresql_data:/var/lib/postgresql/data
      -  ${UF_CONFIG_PATH}/uniflow-postgres:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1

  schellar:
    image: frinx/uniflow-schellar:1.9.2
    environment:
      - LOG_LEVEL=debug
      - CHECK_INTERVAL_SECONDS=10
      - CONDUCTOR_API_URL=http://conductor-server:8080/api
      - BACKEND=postgres
      - POSTGRES_MIGRATIONS_DIR=migrations
      - POSTGRES_DATABASE_URL=host=postgresql port=5432 user=postgres password=postgres database=schellar
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1
    healthcheck:
      test: wget -O /dev/null -q conductor-server:8080 && nc -z postgresql:5432
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  workflow-proxy:
    image: frinx/workflow-proxy:1.0.0
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    healthcheck:
      test: curl --silent --write-out 'HTTPSTATUS:%{http_code}' -X GET 'http://127.0.0.1:8088/probe/liveness'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      placement:
        constraints:
          - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1

volumes:
  uniflow_elastic_data:
    name: uniflow_elastic_data
  uniflow_postgresql_data:
    name: uniflow_postgresql_data

networks:
  default:
    name: frinx-machine
    attachable: true
