global:       
  scrape_interval:     15s # set the scrape interval to every 15 seconds. default is every 1 minute.       
  evaluation_interval: 15s # evaluate rules every 15 seconds. the default is every 1 minute.                       
    
  external_labels:
    monitor: 'prometheus-swarm'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'swarm-node-info'
    dns_sd_configs:
    - names:
      - 'tasks.swarm-node-info'
      type: 'A'
      port: 9100

  - job_name: 'swarm-services-info'
    dns_sd_configs:
    - names:
      - 'tasks.swarm-services-info'
      type: 'A'
      port: 8080

  - job_name: 'krakend'
    dns_sd_configs:
    - names:
      - 'tasks.krakend'
      type: 'A'
      port: 9091
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: krakend      